### ISSUE TITLE
emacs seem to return 0

### ISSUE THREAD

**Issue by hansl** [knownasilya/cli-width#9]

**Comment by knownasilya** [comment]
Not sure that is something I can help with :smile_cat: Most likely it doesn't report it's width correctly. You could always set a default.

**Comment by hansl** [comment]
Worst case if you're about to return 0 you should return the default value passed in.

**Comment by knownasilya** [comment]
We do return the default if any of the other methods return `0`.

**Comment by hansl** [comment]
`index.js` line 41 don't return the default value if it's `0`. I'm not 100% sure what emacs return here, but it's the only case where I can see it returning 0.

**Comment by knownasilya** [comment]
True, but `CLI_WIDTH` is not a standard thing that anyone is setting, that is an option I added to override the default via envs. Would take a PR to use the default if that is 0.
